@host = http://localhost:5130

### Get
GET {{host}}/api/blocks/chain

### Add 1
POST {{host}}/api/blocks/block
Content-Type: application/json

{
  "transactions": [
    {
      "from": "Fikri",
      "to": "Binance",
      "amount": 1000000
    },
    {
      "from": "Avishena",
      "to": "Binance",
      "amount": 20000000
    }
  ]
}

### Add 2
POST {{host}}/api/blocks/block
Content-Type: application/json

{
  "transactions": [
    {
      "from": "Kavic",
      "to": "Binance",
      "amount": 30000000
    }
  ]
}